---
engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
    - "**.php"
    - "**.module"
    - "**.inc"
exclude_paths:
  - tests/*
  - doc/*
  - "*.yml"
  - "*.json"
  - "composer.lock"
  - ".gitattributes"
  - ".gitignore"
  - "LICENSE"
  - "README.md"
  - "phpunit.xml.dist"

