language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.4

before_script: composer install --dev
script: phpunit --configuration phpunit.xml.dist
after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 2bc531c0e3d7518efaa9c79107393ec0d236a45bdff81ce4228f41c5056b8ebe
