#
#  This file is part of TorrentGhost project.
#  You are using it at your own risk and you are fully responsible
#   for everything that code will do.
#
#  (c) Grzegorz Zdanowski <grzegorz@noflash.pl>
#
#  For the full copyright and license information, please view the LICENSE
#   file that was distributed with this source code.
#

torrentGhost:
  filesSavePath: ./
  fileSizeLimit: 25M

dataSources:
  OpenSourceTracker:
    type: fifo
    path: /tmp/os_tracker_log.fifo
    nameExtractPattern: '/^(.*?) \-/'
    linkExtractPattern: '/\- (.*?)$/'
    linkTransformPattern: ['/^(.*?)$/', '$1?passkey=1234']
#    linkCookies:
#      ssid: 1234
#      user_logged: 1
#    filesSavePath: /home/torrents/incomming/opensourcetracker/

  AnotherOSTracker:
    type: rss
    url: http://another-os-tracker.tld/feed.rss
    interval: 300
    nameTagName: title
    nameExtractPattern: '/^(.*?)$/'
    linkTagName: link
    linkExtractPattern: '/^(.*?)$/'
    linkTransformPattern: ['/^(.*?)$/', '$1?downloadKey=4312']
#    linkCookies:
#      session: 321
#    filesSavePath: /home/torrents/incomming/anotheropensourcetracker/

downloadRules:
  Ubuntu:
#    sources: [OpenSourceTracker, AnotherOSTracker]
    nameContainsPattern: '/ubuntu/i'
    nameNotContainsPattern: '/book|video/i'
#    filesSavePath: /home/torrents/incomming/ubuntu/
#    runOnMatch: /usr/bin/app %ruleName %sourceName %matchedName %fileName %filePath
#    disableAfterMatch: true
